#!/usr/bin/python3 -u

import argparse
import contextlib
import fcntl
import os
import sys
import subprocess
import time


MODEM_NETDEV = 'usb0'
MODEM_USB_VENDOR = '19d2'  # ZTE

TEST_HOSTS = [
    "8.8.8.8",
    "8.8.4.4",
    ]
TEST_INTERVAL_SECS = 300  # 5 mins


def main():
    args = parse_args()
    print("running")

    with contextlib.suppress(KeyboardInterrupt):
        while True:
            time.sleep(TEST_INTERVAL_SECS)

            if is_default_route_via_dev(MODEM_NETDEV):
                print("link is using USB modem")
                if ping_hosts(TEST_HOSTS):
                    print("link ok")
                else:
                    print("link NOT ok")
                    run_action(args.action)
            else:
                print("link is not using USB modem")


def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument('action', choices=["usbreset", "reboot", "log"])
    return parser.parse_args()


def is_default_route_via_dev(netdev):
    output = subprocess.check_output(["ip", "route"], universal_newlines=True)
    search = ' dev ' + netdev + ' '
    for line in output.splitlines():
        if line.startswith("default via") and search in line:
            return True
    return False


def ping_hosts(addrs):
    # Try a number of times to allow for flaky connections. We want to
    # be really sure the link is down before taking action.
    for _ in range(5):
        for addr in addrs:
            if ping_host(addr):
                return True
    return False


def ping_host(addr):
    try:
        subprocess.check_call(
            [
                'ping',
                '-n', '-q',    # no DNS, quiet output
                '-c', '1',     # just need one response
                '-w', '30',    # wait up to 30s
                addr,
            ],
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL)
    except subprocess.CalledProcessError:
        return False
    return True


def run_action(action):
    if action == 'usbreset':
        usbreset(MODEM_USB_VENDOR)
    elif action == 'reboot':
        reboot()


def usbreset(vendor):
    path = find_modem_usb_dev(vendor)
    print('sending USB reset to ' + path)
    usb_reset(path)


def find_modem_usb_dev(vendor):
    output = subprocess.check_output(["lsusb", "-d", vendor+':'], universal_newlines=True)
    line = output.splitlines()[0].split()
    assert line[0] == 'Bus'
    assert line[2] == 'Device'
    return '/dev/bus/usb/{}/{}'.format(line[1], line[3][:-1])


USBDEVFS_RESET = ord('U') << (4*2) | 20

def usb_reset(dev_path):
    fd = os.open(dev_path, os.O_WRONLY)
    try:
        fcntl.ioctl(fd, USBDEVFS_RESET, 0)
    finally:
        os.close(fd)


def reboot():
    print('rebooting system')
    subprocess.check_call(["/sbin/reboot"])


if __name__ == '__main__':
    main()
